### ISSUE TITLE
右上角的 menu icon 點下去就消失了

### ISSUE THREAD

**Issue by KimberlyYen** [over-engineering-run/over-engineering-frontend#11]
右上角的 icon 點下去就消失了，以目前的操作上會感到困惑。
---
以下是一個討論。
1. 目前沒功能？
2. 未來有功能？
3. 等有功能再放？
4. 給它一個功能？
---
![截圖 2022-08-09 上午10 37 05](https://user-images.githubusercontent.com/87320011/183551617-73b4efe2-68e3-4f00-ab0e-1ee2f5da67af.png)

**Comment by kayac-chang** [comment]
remove menu for now
