### ISSUE TITLE
搜尋後，文章結果被遮住了

### ISSUE THREAD

**Issue by KimberlyYen** [over-engineering-run/over-engineering-frontend#3]
# 執行步驟重現：
## 搜尋 -> 滑下方文章瀏覽 -> 搜尋提示沒有自動關閉

![319869](https://user-images.githubusercontent.com/87320011/183452560-4f00b0a4-bd9d-49f2-b94a-fd644d24905f.jpg)

**Comment by kayac-chang** [comment]
solved by #7
