### ISSUE TITLE
搜尋結果提示，不是我曾經的搜尋紀錄結果

### ISSUE THREAD

**Issue by KimberlyYen** [over-engineering-run/over-engineering-frontend#4]
Apple
Banna...等等的搜尋結果(如圖所示)

不是我曾經的搜尋紀錄結果
![319869](https://user-images.githubusercontent.com/87320011/183459645-edc1e154-1c70-4ec2-bd0a-b58e9d7fc667.jpg)

**Comment by kayac-chang** [comment]
solved by #9
